/**
 * Brand marks for DevDocs sets, keyed by docset family (the slug before `~`).
 *
 * The ids come from Iconify's `logos` collection — full-colour SVGs served
 * key-less and CORS-open from api.iconify.design, the same source the icon
 * explorer uses. Anything without a logo falls back to a tinted monogram.
 */

import { iconSvgUrl } from "./iconify";

const ICONS: Record<string, string> = {
  angular: "logos:angular-icon",
  angularjs: "logos:angular-icon",
  ansible: "logos:ansible",
  apache_http_server: "logos:apache",
  apache_pig: "logos:apache",
  astro: "logos:astro-icon",
  axios: "logos:axios",
  babel: "logos:babel",
  backbone: "logos:backbone-icon",
  bash: "logos:bash-icon",
  bazel: "devicon:bazel",
  bootstrap: "logos:bootstrap",
  bottle: "logos:python",
  bower: "logos:bower",
  browser_support_tables: "logos:chrome",
  bun: "logos:bun",
  c: "logos:c",
  cakephp: "logos:cakephp-icon",
  celery: "simple-icons:celery",
  chai: "logos:chai",
  chef: "logos:chef",
  click: "logos:python",
  clojure: "logos:clojure",
  cmake: "devicon:cmake",
  codeception: "logos:php",
  codeceptjs: "logos:javascript",
  codeigniter: "logos:codeigniter-icon",
  coffeescript: "logos:coffeescript",
  composer: "logos:composer",
  cordova: "logos:cordova",
  couchdb: "logos:couchdb-icon",
  cpp: "logos:c-plusplus",
  crystal: "logos:crystal",
  css: "logos:css-3",
  cypress: "logos:cypress-icon",
  d3: "logos:d3",
  dart: "logos:dart",
  deno: "logos:deno",
  django: "logos:django-icon",
  django_rest_framework: "logos:django-icon",
  docker: "logos:docker-icon",
  dojo: "logos:dojo-toolkit",
  dom: "logos:chrome",
  drupal: "logos:drupal-icon",
  duckdb: "devicon:duckdb",
  electron: "logos:electron",
  elixir: "devicon:elixir",
  ember: "logos:ember",
  erlang: "logos:erlang",
  esbuild: "logos:esbuild",
  eslint: "logos:eslint",
  express: "logos:express",
  falcon: "logos:python",
  fastapi: "logos:fastapi-icon",
  fish: "devicon:fish",
  flask: "logos:flask",
  flow: "logos:flow",
  gcc: "logos:c-plusplus",
  git: "logos:git-icon",
  go: "logos:go",
  godot: "logos:godot-icon",
  gradle: "logos:gradle",
  graphviz: "vscode-icons:file-type-graphviz",
  groovy: "devicon:groovy",
  grunt: "logos:grunt",
  gtk: "simple-icons:gtk",
  handlebars: "logos:handlebars",
  hapi: "logos:hapi",
  haskell: "logos:haskell-icon",
  haxe: "logos:haxe",
  homebrew: "logos:homebrew",
  html: "logos:html-5",
  htmx: "logos:htmx",
  http: "logos:chrome",
  immutable: "logos:immutable",
  influxdata: "logos:influxdb-icon",
  jasmine: "logos:jasmine",
  javascript: "logos:javascript",
  jekyll: "logos:jekyll",
  jest: "logos:jest",
  jinja: "simple-icons:jinja",
  jquery: "logos:jquery",
  jquerymobile: "logos:jquery",
  jqueryui: "logos:jquery",
  julia: "logos:julia",
  koa: "logos:koa",
  kotlin: "logos:kotlin-icon",
  kubectl: "logos:kubernetes",
  kubernetes: "logos:kubernetes",
  laravel: "logos:laravel",
  latex: "devicon:latex",
  leaflet: "logos:leaflet",
  less: "logos:less",
  lit: "logos:lit-icon",
  lodash: "logos:lodash",
  lua: "logos:lua",
  man: "logos:linux-tux",
  mariadb: "logos:mariadb-icon",
  markdown: "logos:markdown",
  matplotlib: "logos:matplotlib-icon",
  meteor: "logos:meteor-icon",
  minitest: "logos:ruby",
  mocha: "logos:mocha",
  mongoose: "devicon:mongoose",
  moment: "logos:momentjs",
  moment_timezone: "logos:momentjs",
  nextjs: "logos:nextjs-icon",
  nginx: "logos:nginx",
  nginx_lua_module: "logos:nginx",
  nim: "logos:nim-lang",
  nix: "devicon:nixos",
  node: "logos:nodejs-icon",
  nokogiri: "logos:ruby",
  npm: "logos:npm-icon",
  numpy: "logos:numpy",
  ocaml: "logos:ocaml",
  octave: "simple-icons:octave",
  opengl: "logos:opengl",
  openjdk: "logos:java",
  openlayers: "logos:openlayers",
  opentofu: "simple-icons:opentofu",
  padrino: "logos:ruby",
  pandas: "logos:pandas-icon",
  perl: "logos:perl",
  phalcon: "logos:phalcon",
  phoenix: "logos:phoenix",
  php: "logos:php",
  phpunit: "logos:php",
  playwright: "logos:playwright",
  polars: "simple-icons:polars",
  postgresql: "logos:postgresql",
  powershell: "devicon:powershell",
  prettier: "logos:prettier",
  pug: "logos:pug",
  puppeteer: "logos:puppeteer",
  pygame: "logos:python",
  python: "logos:python",
  pytorch: "logos:pytorch-icon",
  qt: "logos:qt",
  r: "logos:r-lang",
  rabbitmq: "logos:rabbitmq-icon",
  rails: "logos:rails",
  react: "logos:react",
  react_bootstrap: "logos:react",
  react_native: "logos:react",
  react_router: "logos:react-router",
  reactivex: "logos:reactivex",
  redis: "logos:redis",
  redux: "logos:redux",
  relay: "logos:relay",
  requests: "logos:python",
  rethinkdb: "logos:rethinkdb",
  ruby: "logos:ruby",
  rust: "logos:rust",
  rxjs: "logos:reactivex",
  saltstack: "vscode-icons:file-type-saltstack",
  sass: "logos:sass",
  scala: "logos:scala",
  scikit_image: "logos:python",
  sequelize: "logos:sequelize",
  socketio: "logos:socket-io",
  spring_boot: "logos:spring-icon",
  sqlite: "logos:sqlite",
  svelte: "logos:svelte-icon",
  svg: "logos:svg",
  symfony: "logos:symfony",
  tailwindcss: "logos:tailwindcss-icon",
  tensorflow: "logos:tensorflow",
  tensorflow_cpp: "logos:tensorflow",
  terraform: "logos:terraform-icon",
  threejs: "logos:threejs",
  twig: "vscode-icons:file-type-twig",
  typescript: "logos:typescript-icon",
  underscore: "simple-icons:underscoredotjs",
  vagrant: "logos:vagrant-icon",
  vite: "logos:vitejs",
  vitest: "logos:vitest",
  vue: "logos:vue",
  vue_router: "logos:vue",
  vueuse: "logos:vueuse",
  vuex: "logos:vue",
  wagtail: "logos:wagtail",
  web_extensions: "logos:firefox",
  webpack: "logos:webpack",
  werkzeug: "logos:python",
  wordpress: "logos:wordpress-icon",
  yarn: "logos:yarn",
  zig: "logos:zig",
  zsh: "logos:bash-icon",
};

/** The Iconify id for a docset family, e.g. `logos:python`. Null when unmapped. */
export function docsetIconId(family: string): string | null {
  return ICONS[family] ?? null;
}

/** The Iconify SVG URL for a docset family, or null when it has no logo. */
export function docsetIconUrl(family: string): string | null {
  const id = ICONS[family];
  return id ? iconSvgUrl(id, { width: 48 }) : null;
}

/**
 * Sets that ship flat single-colour glyphs. Those are painted with the current
 * text colour instead of loaded as-is, so they stay legible in both themes.
 */
export function isFlatIcon(id: string): boolean {
  return id.startsWith("simple-icons:");
}

/**
 * Deterministic hue for a family without a logo, so its monogram tile keeps the
 * same colour everywhere it appears.
 */
export function monogramHue(family: string): number {
  let hash = 0;
  for (let i = 0; i < family.length; i++) hash = (hash * 31 + family.charCodeAt(i)) >>> 0;
  return hash % 360;
}
