import {
  ALargeSmallIcon,
  BarChart3Icon,
  BlendIcon,
  BoxIcon,
  CodeXmlIcon,
  ContrastIcon,
  EraserIcon,
  FingerprintIcon,
  BookOpenIcon,
  ContactIcon,
  FileSpreadsheetIcon,
  Grid3X3Icon,
  HashIcon,
  ImageUpscaleIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  MailIcon,
  MessageSquareIcon,
  PaletteIcon,
  QrCodeIcon,
  RainbowIcon,
  ReceiptTextIcon,
  Share2Icon,
  SmileIcon,
  SwatchBookIcon,
  SparkleIcon,
  SquircleIcon,
  TypeIcon,
  EyeIcon,
  SplineIcon,
  BarcodeIcon,
  SunIcon,
  WandSparklesIcon,
  ScanEyeIcon,
  Code2Icon,
  ShapesIcon,
  BoxSelectIcon,
  DropletsIcon,
  WallpaperIcon,
  Rotate3dIcon,
  VectorSquareIcon,
  ApertureIcon,
  LinkIcon,
  PaintbrushIcon,
  ImageIcon,
  BookMarkedIcon,
  LayoutTemplateIcon,
  VenetianMaskIcon,
  Layers2Icon,
  GripIcon,
  GlassesIcon,
  AudioLinesIcon,
  DnaIcon,
  AnvilIcon,
  SmartphoneIcon,
  SignpostIcon,
  FrameIcon,
  GalleryHorizontalEndIcon,
  type LucideIcon,
} from "lucide-react";
import { WhatsAppIcon } from "@/components/shared/brand-icons";
import type { ToolCategory, ToolMeta } from "@/types";

export const TOOLS = [
  {
    id: "editor",
    slug: "/tools/live-editor",
    name: "Live Code Editor",
    shortName: "Live Editor",
    description:
      "Write HTML, CSS and JavaScript and watch the page rebuild as you type — with Emmet, autocomplete, a real console, an element inspector and one-link sharing.",
    keywords: [
      "online html css js editor",
      "live code editor",
      "html editor online",
      "css playground",
      "javascript playground",
      "code sandbox online",
      "emmet online",
    ],
    icon: CodeXmlIcon,
    category: "playground",
  },
  {
    id: "whatsapp",
    slug: "/tools/whatsapp",
    name: "WhatsApp Link Generator",
    shortName: "WhatsApp",
    description:
      "Create click-to-chat WhatsApp links with a prefilled message, format group invites, and bulk-generate links from a CSV of numbers.",
    keywords: ["whatsapp link generator", "wa.me", "click to chat", "whatsapp qr"],
    icon: WhatsAppIcon,
    category: "links",
  },
  {
    id: "qr",
    slug: "/tools/qr",
    name: "QR Code Generator",
    shortName: "QR Code",
    description:
      "Generate QR codes for URLs, text, phone numbers, email, WiFi networks and vCards. Customize colors, size, error correction and add your logo.",
    keywords: ["qr code generator", "wifi qr code", "custom qr code", "vcard qr"],
    icon: QrCodeIcon,
    category: "links",
  },
  {
    id: "share",
    slug: "/tools/share",
    name: "Share Link Generator",
    shortName: "Share Links",
    description:
      "Build share links for WhatsApp, Telegram, X, Facebook, LinkedIn, Reddit and email — plus a native share button for mobile.",
    keywords: ["share link generator", "social share links", "share button"],
    icon: Share2Icon,
    category: "links",
  },
  {
    id: "sms",
    slug: "/tools/sms",
    name: "SMS Link Generator",
    shortName: "SMS",
    description:
      "Create sms: links that open the messaging app with the number and message already filled in. Perfect for ads, posters and email signatures.",
    keywords: ["sms link generator", "sms link", "text message link"],
    icon: MessageSquareIcon,
    category: "links",
  },
  {
    id: "email",
    slug: "/tools/email",
    name: "Email Link Generator",
    shortName: "Email",
    description:
      "Compose mailto: links with subject, body, CC and BCC prefilled. Great for support buttons, signatures and landing pages.",
    keywords: ["mailto link generator", "email link", "mailto builder"],
    icon: MailIcon,
    category: "links",
  },
  {
    id: "vcard",
    slug: "/tools/vcard",
    name: "vCard Generator",
    shortName: "vCard",
    description:
      "Build a complete vCard 3.0 contact card, preview it live, download the .vcf file and share it as a scannable QR code.",
    keywords: ["vcard generator", "vcf file", "digital business card", "contact qr"],
    icon: ContactIcon,
    category: "links",
  },
  {
    id: "utm",
    slug: "/tools/utm",
    name: "UTM Link Builder",
    shortName: "UTM",
    description:
      "Append UTM parameters to any URL with handy presets for common channels. Keep your analytics clean and consistent.",
    keywords: ["utm builder", "utm link generator", "campaign url builder"],
    icon: BarChart3Icon,
    category: "links",
  },
  {
    id: "password",
    slug: "/tools/password",
    name: "Password Generator",
    shortName: "Password",
    description:
      "Generate cryptographically secure passwords, memorable passphrases and PINs with live entropy and crack-time estimates. Passwords are never stored or logged.",
    keywords: [
      "password generator",
      "strong password",
      "passphrase generator",
      "random password",
      "pin generator",
    ],
    icon: KeyRoundIcon,
    category: "utilities",
  },
  {
    id: "hash",
    slug: "/tools/hash",
    name: "Hash Generator",
    shortName: "Hash",
    description:
      "Compute MD5, SHA-1, SHA-256, SHA-384, SHA-512 and CRC32 hashes of any text or file — with HMAC signing and checksum verification. Verify downloads and sign payloads in seconds.",
    keywords: [
      "hash generator",
      "sha256 generator",
      "md5 hash",
      "checksum calculator",
      "hmac generator",
      "file hash",
    ],
    icon: HashIcon,
    category: "utilities",
  },
  {
    id: "lorem",
    slug: "/tools/lorem",
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum",
    description:
      "Generate lorem ipsum paragraphs, sentences or words with live word counts — as plain text, HTML or Markdown, with optional bold, italic and link markup for testing rich layouts.",
    keywords: [
      "lorem ipsum generator",
      "placeholder text",
      "dummy text generator",
      "filler text",
      "lorem ipsum html",
    ],
    icon: TypeIcon,
    category: "type",
  },
  {
    id: "readtime",
    slug: "/tools/reading-time",
    name: "Reading Time Calculator",
    shortName: "Reading Time",
    description:
      "Paste any text to get reading and speaking time at adjustable speeds, full word and sentence stats, and a Flesch readability score — with Medium-style image time included.",
    keywords: [
      "reading time calculator",
      "read time estimator",
      "words per minute",
      "speaking time calculator",
      "readability score",
    ],
    icon: BookOpenIcon,
    category: "type",
  },
  {
    id: "mockup",
    slug: "/tools/mockup",
    name: "3D Device Mockups",
    shortName: "3D Mockup",
    description:
      "Put your screenshot or video on a real 3D phone or tablet — grab the device and spin it in true perspective, with lit metal edges, floor shadows, five finishes and studio backdrops. Export a crisp 2× PNG, or a WebM clip of your video playing on the device.",
    keywords: [
      "3d device mockup",
      "iphone mockup generator",
      "ipad mockup",
      "app screenshot mockup",
      "video mockup generator",
    ],
    icon: SmartphoneIcon,
    category: "studio",
  },
  {
    id: "favicon",
    slug: "/tools/favicon",
    name: "Favicon Generator",
    shortName: "Favicon",
    description:
      "Turn any image into a full favicon set — favicon.ico, PNGs for every platform, Apple touch icon, web manifest and paste-ready HTML — then download it all as a ZIP. Includes setup steps for HTML, Next.js, Vite, Nuxt and WordPress.",
    keywords: [
      "favicon generator",
      "favicon.ico generator",
      "apple touch icon",
      "web app manifest",
      "favicon package",
    ],
    icon: SparkleIcon,
    category: "studio",
  },
  {
    id: "jsoncsv",
    slug: "/tools/json-csv",
    name: "JSON to CSV Converter",
    shortName: "JSON to CSV",
    description:
      "Transform nested JSON objects or arrays into flat, clean CSV files for Excel or Google Sheets. Features smart object flattening and instant preview.",
    keywords: ["json to csv", "json flattener", "json converter", "data transform"],
    icon: FileSpreadsheetIcon,
    category: "utilities",
  },
  {
    id: "imagesplitter",
    slug: "/tools/image-splitter",
    name: "Image Splitter",
    shortName: "Grid Splitter",
    description:
      "Split your images into perfect 3x1, 3x3, or custom grids for Instagram. High-quality slices ready for your profile.",
    keywords: ["image splitter", "instagram grid", "grid maker", "image slicer"],
    icon: Grid3X3Icon,
    category: "image",
  },
  {
    id: "grid",
    slug: "/tools/grid",
    name: "CSS Grid Builder",
    shortName: "Grid Builder",
    description:
      "Design CSS Grid layouts visually — drag to draw areas, move and resize them with your mouse, tune track sizes and gaps, then export clean CSS, HTML or Tailwind.",
    keywords: [
      "css grid generator",
      "grid layout builder",
      "grid template areas",
      "visual grid editor",
      "tailwind grid",
    ],
    icon: LayoutGridIcon,
    category: "css",
  },
  {
    id: "foundry",
    slug: "/tools/theme-foundry",
    name: "Theme Foundry",
    shortName: "Foundry",
    description:
      "Forge a complete design system from a single brand color — perceptually even OKLCH color ramps, contrast-checked light and dark themes, font pairings, a modular type scale, spacing, radii and shadows, all previewed live on a mini product page. Export CSS variables, Tailwind v4, a paste-ready shadcn/ui theme, or JSON tokens.",
    keywords: [
      "design system generator",
      "shadcn theme generator",
      "tailwind color palette generator",
      "oklch color ramp generator",
      "dark mode theme generator",
      "brand color scale",
    ],
    icon: AnvilIcon,
    category: "brandlab",
  },
  {
    id: "dna",
    slug: "/tools/design-dna",
    name: "Design DNA",
    shortName: "Design DNA",
    description:
      "Paste any website's URL and get its design system extracted in seconds — the real color palette, font stacks, type scale, spacing steps, shadows, corner radii and CSS design tokens, ranked by actual usage. Export everything as CSS variables, Tailwind theme or JSON and start your next project from a look you love.",
    keywords: [
      "extract website colors",
      "what font does this website use",
      "design system extractor",
      "css design tokens from url",
      "website style guide generator",
      "website color palette finder",
    ],
    icon: DnaIcon,
    category: "brandlab",
  },
  {
    id: "glass",
    slug: "/tools/glass",
    name: "Glassmorphism Generator",
    shortName: "Glassmorphism",
    description:
      "Design frosted-glass cards visually — drag the card over vivid backgrounds while you tune blur, transparency, saturation, tint and highlights, then export CSS or Tailwind with a built-in fallback.",
    keywords: [
      "glassmorphism generator",
      "frosted glass css",
      "backdrop-filter generator",
      "glass effect css",
      "glassmorphism tailwind",
    ],
    icon: BlendIcon,
    category: "css",
  },
  {
    id: "shadow",
    slug: "/tools/shadow",
    name: "Smooth Shadow Generator",
    shortName: "Shadow",
    description:
      "Design layered, naturalistic box-shadows — stack up to eight shadows with smooth penumbra falloff, dial in the light direction, distance, blur and color, then export clean CSS or Tailwind. Far softer than a single drop shadow.",
    keywords: [
      "box shadow generator",
      "css smooth shadow",
      "layered shadow css",
      "soft shadow generator",
      "tailwind box shadow",
    ],
    icon: BoxSelectIcon,
    category: "css",
  },
  {
    id: "mesh",
    slug: "/tools/mesh",
    name: "Mesh Gradient Generator",
    shortName: "Mesh Gradient",
    description:
      "Paint silky mesh gradients the Stripe way — drag color blobs around the canvas, shuffle harmonious palettes, add film grain, then export pure-CSS radial gradients, a standalone SVG, or a PNG.",
    keywords: [
      "mesh gradient generator",
      "css mesh gradient",
      "gradient mesh background",
      "stripe gradient",
      "svg mesh gradient",
    ],
    icon: DropletsIcon,
    category: "backgrounds",
  },
  {
    id: "pattern",
    slug: "/tools/pattern",
    name: "CSS Pattern Generator",
    shortName: "Patterns",
    description:
      "Build seamless background patterns from pure CSS — dots, grids, stripes, checks, crosshatch, triangles and zigzag. Tune tile size, weight, angle, opacity and colors, then export CSS, Tailwind or SVG. Razor-sharp at any zoom, zero image weight.",
    keywords: [
      "css pattern generator",
      "background pattern css",
      "css dots grid pattern",
      "repeating background generator",
      "hero patterns alternative",
    ],
    icon: WallpaperIcon,
    category: "backgrounds",
  },
  {
    id: "transform3d",
    slug: "/tools/3d-transform",
    name: "3D Transform Studio",
    shortName: "3D Transform",
    description:
      "Orbit any element in 3D — drag to tilt, then tune perspective, rotation, depth and scale with live light glare and a reactive floor shadow. Export the transform as CSS, Tailwind, or a drop-in pointer-tilt JS snippet for hover effects.",
    keywords: [
      "css 3d transform generator",
      "perspective generator",
      "rotateX rotateY css",
      "3d card tilt effect",
      "hover tilt javascript",
    ],
    icon: Rotate3dIcon,
    category: "css",
  },
  {
    id: "clippath",
    slug: "/tools/clip-path",
    name: "Clip-Path Editor",
    shortName: "Clip Path",
    description:
      "Carve any element into a custom shape — drag polygon handles on a live preview, start from 16 ready-made shapes, add or remove points, and clip your own image. Export the clip-path as CSS or Tailwind.",
    keywords: [
      "clip-path generator",
      "css clip path polygon",
      "image shape mask css",
      "clippy alternative",
      "polygon clip path editor",
    ],
    icon: VectorSquareIcon,
    category: "backgrounds",
  },
  {
    id: "filterlab",
    slug: "/tools/filter-lab",
    name: "CSS Filter Lab",
    shortName: "Filter Lab",
    description:
      "Tune photo filters live and compare with a draggable before/after split — brightness, contrast, saturation, hue, sepia, grayscale, invert, blur and a real drop-shadow. Start from 12 looks, drop in your own photo, then export the filter as CSS or Tailwind.",
    keywords: [
      "css filter generator",
      "image filter css",
      "photo filter editor",
      "before after compare slider",
      "css drop-shadow filter",
    ],
    icon: ApertureIcon,
    category: "css",
  },
  {
    id: "gradient",
    slug: "/tools/gradient",
    name: "Gradient Generator",
    shortName: "Gradient",
    description:
      "Craft linear, radial and conic CSS gradients with full stop control, curated presets and a smart randomizer — then export CSS, Tailwind or SVG.",
    keywords: [
      "css gradient generator",
      "linear gradient",
      "radial gradient",
      "conic gradient",
      "tailwind gradient",
    ],
    icon: RainbowIcon,
    category: "backgrounds",
  },
  {
    id: "palette",
    slug: "/tools/palette",
    name: "Color Palette Generator",
    shortName: "Palette",
    description:
      "Generate harmonious color palettes with color-theory modes — lock the colors you love and shuffle the rest, then export CSS variables, SCSS, JSON or Tailwind.",
    keywords: [
      "color palette generator",
      "color scheme generator",
      "color harmony",
      "random palette",
      "css color variables",
    ],
    icon: SwatchBookIcon,
    category: "color",
  },
  {
    id: "pantone",
    slug: "/tools/pantone",
    name: "Pantone Color Finder",
    shortName: "Pantone",
    description:
      "Find the closest Pantone colors to any hex, RGB or on-screen color — matched against the full 1,341-ink PMS Solid Coated library and ranked perceptually with the CIEDE2000 formula, not crude RGB distance. Pick a color, eyedrop the screen or browse the library, then copy the exact ink name.",
    keywords: [
      "pantone color finder",
      "hex to pantone",
      "rgb to pantone converter",
      "pantone matching system",
      "closest pantone color",
      "pms color finder",
    ],
    icon: BookMarkedIcon,
    category: "color",
  },
  {
    id: "socialpreview",
    slug: "/tools/social-preview",
    name: "Social Link Preview",
    shortName: "Link Preview",
    description:
      "See exactly how your link unfurls on Google, X, Facebook, Slack and Discord before you ship it — fill in the title, description and image once, watch every card update live, then copy production-ready Open Graph and Twitter meta tags.",
    keywords: [
      "open graph preview",
      "og meta tag generator",
      "twitter card preview",
      "social media preview",
      "link unfurl preview",
      "meta tags generator",
    ],
    icon: LayoutTemplateIcon,
    category: "studio",
  },
  {
    id: "steganography",
    slug: "/tools/steganography",
    name: "Image Secrets",
    shortName: "Image Secrets",
    description:
      "Hide a secret message inside any image — the pixels carry your text invisibly using LSB steganography, with optional AES-256 encryption so only your passphrase can read it. Decode it back just as easily.",
    keywords: [
      "steganography tool",
      "hide message in image",
      "image steganography online",
      "encrypt text in photo",
      "lsb steganography",
      "secret message image",
    ],
    icon: VenetianMaskIcon,
    category: "playground",
  },
  {
    id: "duotone",
    slug: "/tools/duotone",
    name: "Duotone Studio",
    shortName: "Duotone",
    description:
      "Turn any photo into a striking two-tone image — map the shadows to one color and the highlights to another, with curated presets, contrast, midpoint and film-grain controls. Recolor live and export a crisp PNG.",
    keywords: [
      "duotone generator",
      "duotone image maker",
      "two tone photo effect",
      "gradient map image",
      "spotify duotone effect",
      "duotone png export",
    ],
    icon: Layers2Icon,
    category: "image",
  },
  {
    id: "halftone",
    slug: "/tools/halftone",
    name: "Halftone Studio",
    shortName: "Halftone",
    description:
      "Turn any photo into a retro halftone — a rotated screen of dots sized by brightness, the classic newsprint and comic-book look. Choose dot shape, spacing, angle and ink/paper colors, then export a PNG or a crisp, infinitely-scalable SVG for print.",
    keywords: [
      "halftone generator",
      "halftone image maker",
      "comic dot effect",
      "newsprint effect",
      "halftone svg export",
      "dot screen filter",
    ],
    icon: GripIcon,
    category: "image",
  },
  {
    id: "stereogram",
    slug: "/tools/magic-eye",
    name: "Magic Eye Maker",
    shortName: "Magic Eye",
    description:
      "Hide a secret word or shape inside a field of colorful dots — a real autostereogram that pops into 3D when you relax your eyes, just like the 90s Magic Eye posters. Tune the depth, pattern and colors, then download the PNG.",
    keywords: [
      "magic eye generator",
      "autostereogram maker",
      "stereogram generator",
      "hidden 3d image",
      "sirds generator",
      "hidden message image",
    ],
    icon: GlassesIcon,
    category: "playground",
  },
  {
    id: "spectro",
    slug: "/tools/audio-secrets",
    name: "Audio Secrets",
    shortName: "Audio Secrets",
    description:
      "Hide a message or logo inside real sound — type it and get an audio file whose spectrogram literally spells it out, the trick Aphex Twin buried in Windowlicker. Play it, download the WAV, then decode any audio file to reveal what's hidden inside.",
    keywords: [
      "spectrogram art generator",
      "hide message in audio",
      "text to spectrogram",
      "audio steganography",
      "aphex twin spectrogram",
      "spectrogram viewer online",
    ],
    icon: AudioLinesIcon,
    category: "playground",
  },
  {
    id: "neumorphism",
    slug: "/tools/neumorphism",
    name: "Neumorphism Generator",
    shortName: "Neumorphism",
    description:
      "Generate soft-UI elements with auto-derived light and dark shadows from any base color — flat, concave, convex or pressed, with a movable light source. Export CSS or Tailwind.",
    keywords: [
      "neumorphism generator",
      "soft ui css",
      "neumorphic shadow",
      "box-shadow generator",
      "soft ui generator",
    ],
    icon: SquircleIcon,
    category: "css",
  },
  {
    id: "bgremover",
    slug: "/tools/background-remover",
    name: "Background Remover",
    shortName: "BG Remover",
    description:
      "Remove the background from any image — AI segmentation for photos and complex art, instant color-matching for flat graphics, with feathered edges and auto-trim.",
    keywords: [
      "background remover",
      "remove background from image",
      "transparent png maker",
      "white background remover",
      "ai background removal",
    ],
    icon: EraserIcon,
    category: "image",
  },
  {
    id: "colors",
    slug: "/tools/colors",
    name: "Image Color Extractor",
    shortName: "Color Extractor",
    description:
      "Upload an image to extract its dominant colors as a clean palette — copy any swatch as HEX, RGB or HSL, sort by frequency or hue, pick colors from your screen, and export to CSS, SCSS, JSON or Tailwind.",
    keywords: [
      "color extractor",
      "image color picker",
      "palette generator",
      "dominant colors",
      "color palette from image",
    ],
    icon: PaletteIcon,
    category: "color",
  },
  {
    id: "enhancer",
    slug: "/tools/image-converter",
    name: "Image Converter & Resizer",
    shortName: "Converter",
    description:
      "Convert images between PNG, JPEG and WebP, resize or upscale with high-quality resampling, then polish with sharpening, auto levels and color controls. Live file-size estimate.",
    keywords: [
      "image converter",
      "png to webp",
      "jpg to png converter",
      "image resizer",
      "upscale image",
      "compress image",
      "sharpen image",
    ],
    icon: ImageUpscaleIcon,
    category: "image",
  },
  {
    id: "contrast",
    slug: "/tools/contrast-checker",
    name: "Color Contrast Checker",
    shortName: "Contrast",
    description:
      "Check text and background colors against WCAG 2.1 (AA/AAA) and modern APCA contrast — with a live preview, an eyedropper, and a smart fix that nudges any color to the nearest accessible shade.",
    keywords: [
      "contrast checker",
      "wcag contrast",
      "color accessibility",
      "apca contrast",
      "accessible color checker",
      "aa aaa contrast ratio",
    ],
    icon: ContrastIcon,
    category: "color",
  },
  {
    id: "fluid",
    slug: "/tools/fluid-type",
    name: "Fluid Type Scale Generator",
    shortName: "Fluid Type",
    description:
      "Generate responsive CSS clamp() font sizes that scale smoothly between any two viewports — a full modular type scale with a live resize preview. Export to CSS variables or Tailwind.",
    keywords: [
      "fluid typography",
      "css clamp generator",
      "responsive font size",
      "modular type scale",
      "clamp font size",
      "fluid type scale",
    ],
    icon: ALargeSmallIcon,
    category: "type",
  },
  {
    id: "brand",
    slug: "/tools/brand-personality",
    name: "Brand Personality Mapper",
    shortName: "Brand Mapper",
    description:
      "Map your brand on Aaker's five personality dimensions — Sincerity, Excitement, Competence, Sophistication and Ruggedness — and get a live radar chart plus a tailored palette, type, and tone-of-voice kit.",
    keywords: [
      "brand personality",
      "aaker brand dimensions",
      "brand archetype",
      "brand identity tool",
      "brand voice generator",
      "brand strategy",
    ],
    icon: FingerprintIcon,
    category: "brandlab",
  },
  {
    id: "attention",
    slug: "/tools/attention",
    name: "Attention Heatmap",
    shortName: "Attention",
    description:
      "Predict where users will look in your designs. Uses local contrast, edge density and color rarity to generate a visual-attention saliency map and find hotspots.",
    keywords: [
      "attention heatmap",
      "visual attention",
      "saliency map",
      "eye tracking proxy",
      "design hotspot",
    ],
    icon: EyeIcon,
    category: "image",
  },
  {
    id: "easing",
    slug: "/tools/easing",
    name: "Easing & Motion Studio",
    shortName: "Easing",
    description:
      "Shape animation timing visually — drag a cubic-bezier curve or tune a real spring, watch it loop on position, scale, rotation and opacity, then export CSS, Tailwind or Framer. Springs bake down to a modern CSS linear() curve.",
    keywords: [
      "cubic bezier generator",
      "easing function generator",
      "css linear easing",
      "spring animation css",
      "transition timing function",
      "animation curve editor",
    ],
    icon: SplineIcon,
    category: "css",
  },
  {
    id: "barcode",
    slug: "/tools/barcode",
    name: "Barcode Generator",
    shortName: "Barcode",
    description:
      "Make scannable 1D barcodes — Code 128, EAN-13, UPC-A, EAN-8, ITF-14, Code 39, Codabar and Pharmacode. Smart format auto-detection, live validation, full color and density control, crisp SVG or high-res PNG export, and batch-generate a whole list into a ZIP.",
    keywords: [
      "barcode generator",
      "code 128 generator",
      "ean 13 barcode",
      "upc barcode generator",
      "batch barcode generator",
      "barcode svg png",
    ],
    icon: BarcodeIcon,
    category: "links",
  },
  {
    id: "glow",
    slug: "/tools/border-glow",
    name: "Border Glow Generator",
    shortName: "Border Glow",
    description:
      "Design glowing borders for cards and buttons — neon halos, gradient edges, or an animated rotating aurora border with a soft bloom. Tune blur, reach, intensity and speed live on a dark or light stage, then export clean CSS (with a reduced-motion guard) or Tailwind.",
    keywords: [
      "border glow generator",
      "css glow effect",
      "neon border css",
      "gradient border generator",
      "animated border css",
      "glowing card css",
    ],
    icon: SunIcon,
    category: "css",
  },
  {
    id: "typography",
    slug: "/tools/typography",
    name: "Typography Studio",
    shortName: "Typography",
    description:
      "Ten text effects in one studio — gradient, animated gradient, aurora, split-color, metallic, neon, glow, outline, glass and 3D. Edit your headline live, dial in any font, weight and spacing, shuffle harmonious colors, then export clean CSS (reduced-motion safe) or Tailwind.",
    keywords: [
      "gradient text generator",
      "neon text generator",
      "3d text generator",
      "metallic text css",
      "animated gradient text",
      "outline text generator",
      "css text effects",
    ],
    icon: WandSparklesIcon,
    category: "type",
  },
  {
    id: "logo",
    slug: "/tools/logo-tester",
    name: "Logo Visibility Tester",
    shortName: "Logo Tester",
    description:
      "Drop in your logo and see how it really performs — on light, dark, colored and busy backgrounds, shrunk to favicon size, squinted, grayscaled and silhouetted, plus favicon, app-icon and avatar mockups. Get a smart visibility score with graded metrics and plain-English fixes.",
    keywords: [
      "logo visibility tester",
      "logo test tool",
      "favicon preview",
      "logo contrast checker",
      "logo on dark background",
      "logo legibility test",
    ],
    icon: ScanEyeIcon,
    category: "studio",
  },
  {
    id: "codeshot",
    slug: "/tools/code-image",
    name: "Code Image Generator",
    shortName: "Code Image",
    description:
      "Turn any code snippet into a beautiful, shareable image — VS Code-grade syntax highlighting for 20+ languages via Shiki, real editor themes, window chrome, gradient backdrops, line numbers and retina PNG export. Perfect for X, slides, docs and READMEs.",
    keywords: [
      "code image generator",
      "code to image",
      "code screenshot",
      "carbon alternative",
      "beautiful code snippets",
      "syntax highlight image",
    ],
    icon: Code2Icon,
    category: "studio",
  },
  {
    id: "blob",
    slug: "/tools/blob-generator",
    name: "Blob & Wave Generator",
    shortName: "Blobs & Waves",
    description:
      "Generate organic SVG blobs and layered section-divider waves — tune points, randomness, layers and amplitude, shuffle for endless variations, and pour in a gradient. Export crisp SVG, a CSS background snippet, or PNG.",
    keywords: [
      "svg blob generator",
      "blob maker",
      "svg wave generator",
      "section divider svg",
      "organic shape generator",
      "css background shape",
    ],
    icon: ShapesIcon,
    category: "backgrounds",
  },
  {
    id: "logo3d",
    slug: "/tools/3d-logo",
    name: "3D Logo Studio",
    shortName: "3D Logo",
    description:
      "Turn any SVG logo into real 3D — extrude it with bevelled depth, dress it in chrome, gold, glass or neon, grab it and spin it in true perspective over studio backdrops. Export a transparent PNG at up to 4×, or record a WebM of it rotating.",
    keywords: [
      "3d logo maker",
      "svg to 3d",
      "logo 3d effect",
      "chrome logo",
      "3d logo animation",
      "logo mockup 3d",
    ],
    icon: BoxIcon,
    category: "studio",
  },
  {
    id: "invoice",
    slug: "/tools/invoice",
    name: "Invoice Generator",
    shortName: "Invoice",
    description:
      "Create a clean, professional invoice in minutes — your logo and business details, line items with quantities, tax and discounts in any currency, automatic numbering and totals. Everything stays saved in your browser; print it or save it as a PDF with one click.",
    keywords: [
      "invoice generator",
      "free invoice maker",
      "invoice template",
      "invoice pdf",
      "billing tool",
      "freelance invoice",
    ],
    icon: ReceiptTextIcon,
    category: "utilities",
  },
  {
    id: "ogstudio",
    slug: "/tools/og-image",
    name: "OG Image Studio",
    shortName: "OG Studio",
    description:
      "Design social share cards that actually get clicked — mesh, gradient and photo backgrounds, gradient headlines, logos and bylines, film grain and glass. Lay out once, then export a pixel-perfect PNG for Open Graph, X, LinkedIn, stories and YouTube — or copy a drop-in Next.js opengraph-image route that generates it per page.",
    keywords: [
      "og image generator",
      "open graph image maker",
      "social share card generator",
      "twitter card generator",
      "opengraph-image next.js",
      "og image template",
    ],
    icon: FrameIcon,
    category: "studio",
  },
  {
    id: "carousel",
    slug: "/tools/carousel",
    name: "Carousel Maker",
    shortName: "Carousel",
    description:
      "Design swipeable Instagram and LinkedIn carousels that get saved and shared — pick a theme once and every slide stays on-brand, with cover, bullet, quote and call-to-action layouts, gradient headlines, page dots and a swipe hint. Reorder slides live, then export every slide as a crisp PNG or download the whole set as a ZIP.",
    keywords: [
      "carousel maker",
      "instagram carousel generator",
      "linkedin carousel maker",
      "swipe post generator",
      "carousel template",
      "social media carousel",
    ],
    icon: GalleryHorizontalEndIcon,
    category: "studio",
  },
  {
    id: "avatar",
    slug: "/tools/avatar",
    name: "Avatar Generator",
    shortName: "Avatars",
    description:
      "Generate unique avatars in 21 art styles — type any name for a matching face, tweak the background and corners, then export crisp SVG or PNG. Perfect for profiles, placeholders and team pages.",
    keywords: [
      "avatar generator",
      "random avatar",
      "profile picture generator",
      "placeholder avatar",
      "svg avatar",
      "identicon generator",
    ],
    icon: SmileIcon,
    category: "studio",
  },
  {
    id: "slugify",
    slug: "/tools/slugify",
    name: "Slug Generator",
    shortName: "Slugify",
    description:
      "Turn any title into a clean URL slug — accents folded, symbols spelled out, filler words dropped and length capped. Paste a list to slugify hundreds at once.",
    keywords: [
      "slug generator",
      "slugify",
      "url slug maker",
      "seo friendly url",
      "permalink generator",
      "text to slug",
    ],
    icon: SignpostIcon,
    category: "utilities",
  },
] as const satisfies readonly ToolMeta[];

/** Every valid tool id — derived from the registry above, never edit by hand. */
export type ToolId = (typeof TOOLS)[number]["id"];

// Object.fromEntries widens keys to string — the registry guarantees every ToolId is present.
export const TOOL_BY_ID = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
) as unknown as Record<ToolId, ToolMeta>;

/** Human labels, icons + display order for the tools-page sections and filter. */
export const TOOL_CATEGORIES: readonly {
  id: ToolCategory;
  label: string;
  icon: LucideIcon;
  description: string;
}[] = [
  {
    id: "studio",
    label: "Design Studio",
    icon: WandSparklesIcon,
    description:
      "The showpieces — 3D device mockups, 3D logos, code shots, favicons and social cards, exported ready to ship.",
  },
  {
    id: "links",
    label: "Links & QR",
    icon: LinkIcon,
    description: "Click-to-chat links, QR codes, share buttons, contact cards and campaign URLs.",
  },
  {
    id: "image",
    label: "Image Lab",
    icon: ImageIcon,
    description: "Remove backgrounds, upscale, split, stylize — retouch any picture in place.",
  },
  {
    id: "color",
    label: "Color",
    icon: PaletteIcon,
    description: "Palettes, Pantone matching, image color extraction and accessible contrast.",
  },
  {
    id: "backgrounds",
    label: "Backgrounds & Shapes",
    icon: ShapesIcon,
    description: "Gradients, meshes, seamless patterns, blobs and custom clip shapes.",
  },
  {
    id: "css",
    label: "CSS Effects",
    icon: PaintbrushIcon,
    description: "Glass, shadows, glows, grids and 3D tilts — tuned live, exported as clean CSS.",
  },
  {
    id: "type",
    label: "Type & Text",
    icon: TypeIcon,
    description: "Type scales, fluid sizing, placeholder text and reading-time stats.",
  },
  {
    id: "brandlab",
    label: "Brand Lab",
    icon: FingerprintIcon,
    description: "Extract, define and stress-test a visual identity — from any site or your own.",
  },
  {
    id: "utilities",
    label: "Utilities",
    icon: Code2Icon,
    description: "Passwords, hashes, data converters and a professional invoice maker.",
  },
  {
    id: "playground",
    label: "Playground",
    icon: VenetianMaskIcon,
    description:
      "A live code editor, messages hidden inside pixels, 3D dot fields and sound.",
  },
];
