import {
  ALargeSmallIcon,
  BarChart3Icon,
  BlendIcon,
  ContrastIcon,
  EraserIcon,
  FingerprintIcon,
  BookOpenIcon,
  ContactIcon,
  FileSpreadsheetIcon,
  FrameIcon,
  Grid3X3Icon,
  HashIcon,
  ImageUpscaleIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  MailIcon,
  MessageSquareIcon,
  PaletteIcon,
  PhoneIcon,
  QrCodeIcon,
  RainbowIcon,
  Share2Icon,
  SwatchBookIcon,
  SparkleIcon,
  SparklesIcon,
  SquircleIcon,
  TypeIcon,
  EyeIcon,
  SplineIcon,
  BarcodeIcon,
  SunIcon,
  WandSparklesIcon,
  ScanEyeIcon,
  Code2Icon,
  ShapesIcon,
  BoxSelectIcon,
  DropletsIcon,
  WallpaperIcon,
  Rotate3dIcon,
  VectorSquareIcon,
  ApertureIcon,
  LinkIcon,
  PaintbrushIcon,
  ImageIcon,
  BookMarkedIcon,
  type LucideIcon,
} from "lucide-react";
import { WhatsAppIcon } from "@/components/shared/brand-icons";
import type { ToolCategory, ToolMeta } from "@/types";

export const TOOLS = [
  {
    id: "universal",
    slug: "/tools/universal",
    name: "Universal Link Generator",
    shortName: "Universal",
    description:
      "Pick a link type — WhatsApp, SMS, call, email, WiFi or plain URL — and the form morphs instantly. One tool, every protocol.",
    keywords: ["universal link generator", "link builder", "qr generator"],
    icon: SparklesIcon,
    category: "links",
  },
  {
    id: "whatsapp",
    slug: "/tools/whatsapp",
    name: "WhatsApp Link Generator",
    shortName: "WhatsApp",
    description:
      "Create click-to-chat WhatsApp links with a prefilled message, format group invites, and bulk-generate links from a CSV of numbers.",
    keywords: ["whatsapp link generator", "wa.me", "click to chat", "whatsapp qr"],
    icon: WhatsAppIcon,
    category: "links",
  },
  {
    id: "qr",
    slug: "/tools/qr",
    name: "QR Code Generator",
    shortName: "QR Code",
    description:
      "Generate QR codes for URLs, text, phone numbers, email, WiFi networks and vCards. Customize colors, size, error correction and add your logo.",
    keywords: ["qr code generator", "wifi qr code", "custom qr code", "vcard qr"],
    icon: QrCodeIcon,
    category: "links",
  },
  {
    id: "share",
    slug: "/tools/share",
    name: "Share Link Generator",
    shortName: "Share Links",
    description:
      "Build share links for WhatsApp, Telegram, X, Facebook, LinkedIn, Reddit and email — plus a native share button for mobile.",
    keywords: ["share link generator", "social share links", "share button"],
    icon: Share2Icon,
    category: "links",
  },
  {
    id: "sms",
    slug: "/tools/sms",
    name: "SMS Link Generator",
    shortName: "SMS",
    description:
      "Create sms: links that open the messaging app with the number and message already filled in. Perfect for ads, posters and email signatures.",
    keywords: ["sms link generator", "sms link", "text message link"],
    icon: MessageSquareIcon,
    category: "links",
  },
  {
    id: "tel",
    slug: "/tools/tel",
    name: "Click-to-Call Link Generator",
    shortName: "Call",
    description:
      "Generate tel: links that start a phone call with one tap. Validate any international number with a built-in country picker.",
    keywords: ["tel link generator", "click to call", "phone link"],
    icon: PhoneIcon,
    category: "links",
  },
  {
    id: "email",
    slug: "/tools/email",
    name: "Email Link Generator",
    shortName: "Email",
    description:
      "Compose mailto: links with subject, body, CC and BCC prefilled. Great for support buttons, signatures and landing pages.",
    keywords: ["mailto link generator", "email link", "mailto builder"],
    icon: MailIcon,
    category: "links",
  },
  {
    id: "vcard",
    slug: "/tools/vcard",
    name: "vCard Generator",
    shortName: "vCard",
    description:
      "Build a complete vCard 3.0 contact card, preview it live, download the .vcf file and share it as a scannable QR code.",
    keywords: ["vcard generator", "vcf file", "digital business card", "contact qr"],
    icon: ContactIcon,
    category: "links",
  },
  {
    id: "utm",
    slug: "/tools/utm",
    name: "UTM Link Builder",
    shortName: "UTM",
    description:
      "Append UTM parameters to any URL with handy presets for common channels. Keep your analytics clean and consistent.",
    keywords: ["utm builder", "utm link generator", "campaign url builder"],
    icon: BarChart3Icon,
    category: "links",
  },
  {
    id: "password",
    slug: "/tools/password",
    name: "Password Generator",
    shortName: "Password",
    description:
      "Generate cryptographically secure passwords, memorable passphrases and PINs with live entropy and crack-time estimates. Passwords are never stored or logged.",
    keywords: [
      "password generator",
      "strong password",
      "passphrase generator",
      "random password",
      "pin generator",
    ],
    icon: KeyRoundIcon,
    category: "developer",
  },
  {
    id: "hash",
    slug: "/tools/hash",
    name: "Hash Generator",
    shortName: "Hash",
    description:
      "Compute MD5, SHA-1, SHA-256, SHA-384, SHA-512 and CRC32 hashes of any text or file — with HMAC signing and checksum verification. Verify downloads and sign payloads in seconds.",
    keywords: [
      "hash generator",
      "sha256 generator",
      "md5 hash",
      "checksum calculator",
      "hmac generator",
      "file hash",
    ],
    icon: HashIcon,
    category: "developer",
  },
  {
    id: "lorem",
    slug: "/tools/lorem",
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum",
    description:
      "Generate lorem ipsum paragraphs, sentences or words with live word counts — as plain text, HTML or Markdown, with optional bold, italic and link markup for testing rich layouts.",
    keywords: [
      "lorem ipsum generator",
      "placeholder text",
      "dummy text generator",
      "filler text",
      "lorem ipsum html",
    ],
    icon: TypeIcon,
    category: "developer",
  },
  {
    id: "readtime",
    slug: "/tools/reading-time",
    name: "Reading Time Calculator",
    shortName: "Reading Time",
    description:
      "Paste any text to get reading and speaking time at adjustable speeds, full word and sentence stats, and a Flesch readability score — with Medium-style image time included.",
    keywords: [
      "reading time calculator",
      "read time estimator",
      "words per minute",
      "speaking time calculator",
      "readability score",
    ],
    icon: BookOpenIcon,
    category: "developer",
  },
  {
    id: "mockup",
    slug: "/tools/mockup",
    name: "Mockup Generator",
    shortName: "Mockup",
    description:
      "Wrap screenshots, videos and live screen captures in browser, window or phone frames — with gradient backdrops, tilt, shadows and captions. Export social-ready PNGs or WebM video, all composed on-device.",
    keywords: [
      "mockup generator",
      "screenshot mockup",
      "device frame",
      "browser frame screenshot",
      "video mockup",
      "screen recording frame",
    ],
    icon: FrameIcon,
    category: "image",
  },
  {
    id: "favicon",
    slug: "/tools/favicon",
    name: "Favicon Generator",
    shortName: "Favicon",
    description:
      "Turn any image into a full favicon set — favicon.ico, PNGs for every platform, Apple touch icon, web manifest and paste-ready HTML — then download it all as a ZIP. Includes setup steps for HTML, Next.js, Vite, Nuxt and WordPress.",
    keywords: [
      "favicon generator",
      "favicon.ico generator",
      "apple touch icon",
      "web app manifest",
      "favicon package",
    ],
    icon: SparkleIcon,
    category: "image",
  },
  {
    id: "jsoncsv",
    slug: "/tools/json-csv",
    name: "JSON to CSV Converter",
    shortName: "JSON to CSV",
    description:
      "Transform nested JSON objects or arrays into flat, clean CSV files for Excel or Google Sheets. Features smart object flattening and instant preview.",
    keywords: ["json to csv", "json flattener", "json converter", "data transform"],
    icon: FileSpreadsheetIcon,
    category: "developer",
  },
  {
    id: "imagesplitter",
    slug: "/tools/image-splitter",
    name: "Image Splitter",
    shortName: "Grid Splitter",
    description:
      "Split your images into perfect 3x1, 3x3, or custom grids for Instagram. Locally processed, high-quality slices ready for your profile.",
    keywords: ["image splitter", "instagram grid", "grid maker", "image slicer"],
    icon: Grid3X3Icon,
    category: "image",
  },
  {
    id: "grid",
    slug: "/tools/grid",
    name: "CSS Grid Builder",
    shortName: "Grid Builder",
    description:
      "Design CSS Grid layouts visually — drag to draw areas, move and resize them with your mouse, tune track sizes and gaps, then export clean CSS, HTML or Tailwind.",
    keywords: [
      "css grid generator",
      "grid layout builder",
      "grid template areas",
      "visual grid editor",
      "tailwind grid",
    ],
    icon: LayoutGridIcon,
    category: "developer",
  },
  {
    id: "glass",
    slug: "/tools/glass",
    name: "Glassmorphism Generator",
    shortName: "Glassmorphism",
    description:
      "Design frosted-glass cards visually — drag the card over vivid backgrounds while you tune blur, transparency, saturation, tint and highlights, then export CSS or Tailwind with a built-in fallback.",
    keywords: [
      "glassmorphism generator",
      "frosted glass css",
      "backdrop-filter generator",
      "glass effect css",
      "glassmorphism tailwind",
    ],
    icon: BlendIcon,
    category: "design",
  },
  {
    id: "shadow",
    slug: "/tools/shadow",
    name: "Smooth Shadow Generator",
    shortName: "Shadow",
    description:
      "Design layered, naturalistic box-shadows — stack up to eight shadows with smooth penumbra falloff, dial in the light direction, distance, blur and color, then export clean CSS or Tailwind. Far softer than a single drop shadow. All on-device.",
    keywords: [
      "box shadow generator",
      "css smooth shadow",
      "layered shadow css",
      "soft shadow generator",
      "tailwind box shadow",
    ],
    icon: BoxSelectIcon,
    category: "design",
  },
  {
    id: "mesh",
    slug: "/tools/mesh",
    name: "Mesh Gradient Generator",
    shortName: "Mesh Gradient",
    description:
      "Paint silky mesh gradients the Stripe way — drag color blobs around the canvas, shuffle harmonious palettes, add film grain, then export pure-CSS radial gradients, a standalone SVG, or a PNG. All on-device.",
    keywords: [
      "mesh gradient generator",
      "css mesh gradient",
      "gradient mesh background",
      "stripe gradient",
      "svg mesh gradient",
    ],
    icon: DropletsIcon,
    category: "color",
  },
  {
    id: "pattern",
    slug: "/tools/pattern",
    name: "CSS Pattern Generator",
    shortName: "Patterns",
    description:
      "Build seamless background patterns from pure CSS — dots, grids, stripes, checks, crosshatch, triangles and zigzag. Tune tile size, weight, angle, opacity and colors, then export CSS, Tailwind or SVG. Razor-sharp at any zoom, zero image weight. All on-device.",
    keywords: [
      "css pattern generator",
      "background pattern css",
      "css dots grid pattern",
      "repeating background generator",
      "hero patterns alternative",
    ],
    icon: WallpaperIcon,
    category: "design",
  },
  {
    id: "transform3d",
    slug: "/tools/3d-transform",
    name: "3D Transform Studio",
    shortName: "3D Transform",
    description:
      "Orbit any element in 3D — drag to tilt, then tune perspective, rotation, depth and scale with live light glare and a reactive floor shadow. Export the transform as CSS, Tailwind, or a drop-in pointer-tilt JS snippet for hover effects. All on-device.",
    keywords: [
      "css 3d transform generator",
      "perspective generator",
      "rotateX rotateY css",
      "3d card tilt effect",
      "hover tilt javascript",
    ],
    icon: Rotate3dIcon,
    category: "design",
  },
  {
    id: "clippath",
    slug: "/tools/clip-path",
    name: "Clip-Path Editor",
    shortName: "Clip Path",
    description:
      "Carve any element into a custom shape — drag polygon handles on a live preview, start from 16 ready-made shapes, add or remove points, and clip your own image. Export the clip-path as CSS or Tailwind. All on-device.",
    keywords: [
      "clip-path generator",
      "css clip path polygon",
      "image shape mask css",
      "clippy alternative",
      "polygon clip path editor",
    ],
    icon: VectorSquareIcon,
    category: "design",
  },
  {
    id: "filterlab",
    slug: "/tools/filter-lab",
    name: "CSS Filter Lab",
    shortName: "Filter Lab",
    description:
      "Tune photo filters live and compare with a draggable before/after split — brightness, contrast, saturation, hue, sepia, grayscale, invert, blur and a real drop-shadow. Start from 12 looks, drop in your own photo, then export the filter as CSS or Tailwind. All on-device.",
    keywords: [
      "css filter generator",
      "image filter css",
      "photo filter editor",
      "before after compare slider",
      "css drop-shadow filter",
    ],
    icon: ApertureIcon,
    category: "design",
  },
  {
    id: "gradient",
    slug: "/tools/gradient",
    name: "Gradient Generator",
    shortName: "Gradient",
    description:
      "Craft linear, radial and conic CSS gradients with full stop control, curated presets and a smart randomizer — then export CSS, Tailwind or SVG.",
    keywords: [
      "css gradient generator",
      "linear gradient",
      "radial gradient",
      "conic gradient",
      "tailwind gradient",
    ],
    icon: RainbowIcon,
    category: "color",
  },
  {
    id: "palette",
    slug: "/tools/palette",
    name: "Color Palette Generator",
    shortName: "Palette",
    description:
      "Generate harmonious color palettes with color-theory modes — lock the colors you love and shuffle the rest, then export CSS variables, SCSS, JSON or Tailwind.",
    keywords: [
      "color palette generator",
      "color scheme generator",
      "color harmony",
      "random palette",
      "css color variables",
    ],
    icon: SwatchBookIcon,
    category: "color",
  },
  {
    id: "pantone",
    slug: "/tools/pantone",
    name: "Pantone Color Finder",
    shortName: "Pantone",
    description:
      "Find the closest Pantone colors to any hex, RGB or on-screen color — matched perceptually with the CIEDE2000 formula, not crude RGB distance. Pick a color, eyedrop the screen or browse the PMS library, then copy the exact ink name.",
    keywords: [
      "pantone color finder",
      "hex to pantone",
      "rgb to pantone converter",
      "pantone matching system",
      "closest pantone color",
      "pms color finder",
    ],
    icon: BookMarkedIcon,
    category: "color",
  },
  {
    id: "neumorphism",
    slug: "/tools/neumorphism",
    name: "Neumorphism Generator",
    shortName: "Neumorphism",
    description:
      "Generate soft-UI elements with auto-derived light and dark shadows from any base color — flat, concave, convex or pressed, with a movable light source. Export CSS or Tailwind.",
    keywords: [
      "neumorphism generator",
      "soft ui css",
      "neumorphic shadow",
      "box-shadow generator",
      "soft ui generator",
    ],
    icon: SquircleIcon,
    category: "design",
  },
  {
    id: "bgremover",
    slug: "/tools/background-remover",
    name: "Background Remover",
    shortName: "BG Remover",
    description:
      "Remove the background from any image in your browser — AI segmentation for photos and complex art, instant color-matching for flat graphics, with feathered edges and auto-trim. Nothing is ever uploaded.",
    keywords: [
      "background remover",
      "remove background from image",
      "transparent png maker",
      "white background remover",
      "ai background removal",
    ],
    icon: EraserIcon,
    category: "image",
  },
  {
    id: "colors",
    slug: "/tools/colors",
    name: "Image Color Extractor",
    shortName: "Color Extractor",
    description:
      "Upload an image to extract its dominant colors as a clean palette — copy any swatch as HEX, RGB or HSL, sort by frequency or hue, pick colors from your screen, and export to CSS, SCSS, JSON or Tailwind. All on-device.",
    keywords: [
      "color extractor",
      "image color picker",
      "palette generator",
      "dominant colors",
      "color palette from image",
    ],
    icon: PaletteIcon,
    category: "color",
  },
  {
    id: "enhancer",
    slug: "/tools/image-converter",
    name: "Image Converter & Resizer",
    shortName: "Converter",
    description:
      "Convert images between PNG, JPEG and WebP, resize or upscale with high-quality resampling, then polish with sharpening, auto levels and color controls. Live file-size estimate — entirely on-device.",
    keywords: [
      "image converter",
      "png to webp",
      "jpg to png converter",
      "image resizer",
      "upscale image",
      "compress image",
      "sharpen image",
    ],
    icon: ImageUpscaleIcon,
    category: "image",
  },
  {
    id: "contrast",
    slug: "/tools/contrast-checker",
    name: "Color Contrast Checker",
    shortName: "Contrast",
    description:
      "Check text and background colors against WCAG 2.1 (AA/AAA) and modern APCA contrast — with a live preview, an eyedropper, and a smart fix that nudges any color to the nearest accessible shade. All on-device.",
    keywords: [
      "contrast checker",
      "wcag contrast",
      "color accessibility",
      "apca contrast",
      "accessible color checker",
      "aa aaa contrast ratio",
    ],
    icon: ContrastIcon,
    category: "color",
  },
  {
    id: "fluid",
    slug: "/tools/fluid-type",
    name: "Fluid Type Scale Generator",
    shortName: "Fluid Type",
    description:
      "Generate responsive CSS clamp() font sizes that scale smoothly between any two viewports — a full modular type scale with a live resize preview. Export to CSS variables or Tailwind. All on-device.",
    keywords: [
      "fluid typography",
      "css clamp generator",
      "responsive font size",
      "modular type scale",
      "clamp font size",
      "fluid type scale",
    ],
    icon: ALargeSmallIcon,
    category: "developer",
  },
  {
    id: "brand",
    slug: "/tools/brand-personality",
    name: "Brand Personality Mapper",
    shortName: "Brand Mapper",
    description:
      "Map your brand on Aaker's five personality dimensions — Sincerity, Excitement, Competence, Sophistication and Ruggedness — and get a live radar chart plus a tailored palette, type, and tone-of-voice kit. All on-device.",
    keywords: [
      "brand personality",
      "aaker brand dimensions",
      "brand archetype",
      "brand identity tool",
      "brand voice generator",
      "brand strategy",
    ],
    icon: FingerprintIcon,
    category: "design",
  },
  {
    id: "attention",
    slug: "/tools/attention",
    name: "Attention Heatmap",
    shortName: "Attention",
    description:
      "Predict where users will look in your designs. Uses local contrast, edge density and color rarity to generate a visual-attention saliency map and find hotspots — all on-device.",
    keywords: [
      "attention heatmap",
      "visual attention",
      "saliency map",
      "eye tracking proxy",
      "design hotspot",
    ],
    icon: EyeIcon,
    category: "image",
  },
  {
    id: "easing",
    slug: "/tools/easing",
    name: "Easing & Motion Studio",
    shortName: "Easing",
    description:
      "Shape animation timing visually — drag a cubic-bezier curve or tune a real spring, watch it loop on position, scale, rotation and opacity, then export CSS, Tailwind or Framer. Springs bake down to a modern CSS linear() curve. All on-device.",
    keywords: [
      "cubic bezier generator",
      "easing function generator",
      "css linear easing",
      "spring animation css",
      "transition timing function",
      "animation curve editor",
    ],
    icon: SplineIcon,
    category: "design",
  },
  {
    id: "barcode",
    slug: "/tools/barcode",
    name: "Barcode Generator",
    shortName: "Barcode",
    description:
      "Make scannable 1D barcodes — Code 128, EAN-13, UPC-A, EAN-8, ITF-14, Code 39, Codabar and Pharmacode. Smart format auto-detection, live validation, full color and density control, crisp SVG or high-res PNG export, and batch-generate a whole list into a ZIP. All on-device.",
    keywords: [
      "barcode generator",
      "code 128 generator",
      "ean 13 barcode",
      "upc barcode generator",
      "batch barcode generator",
      "barcode svg png",
    ],
    icon: BarcodeIcon,
    category: "links",
  },
  {
    id: "glow",
    slug: "/tools/border-glow",
    name: "Border Glow Generator",
    shortName: "Border Glow",
    description:
      "Design glowing borders for cards and buttons — neon halos, gradient edges, or an animated rotating aurora border with a soft bloom. Tune blur, reach, intensity and speed live on a dark or light stage, then export clean CSS (with a reduced-motion guard) or Tailwind. All on-device.",
    keywords: [
      "border glow generator",
      "css glow effect",
      "neon border css",
      "gradient border generator",
      "animated border css",
      "glowing card css",
    ],
    icon: SunIcon,
    category: "design",
  },
  {
    id: "typography",
    slug: "/tools/typography",
    name: "Typography Studio",
    shortName: "Typography",
    description:
      "Ten text effects in one studio — gradient, animated gradient, aurora, split-color, metallic, neon, glow, outline, glass and 3D. Edit your headline live, dial in any font, weight and spacing, shuffle harmonious colors, then export clean CSS (reduced-motion safe) or Tailwind. All on-device.",
    keywords: [
      "gradient text generator",
      "neon text generator",
      "3d text generator",
      "metallic text css",
      "animated gradient text",
      "outline text generator",
      "css text effects",
    ],
    icon: WandSparklesIcon,
    category: "design",
  },
  {
    id: "logo",
    slug: "/tools/logo-tester",
    name: "Logo Visibility Tester",
    shortName: "Logo Tester",
    description:
      "Drop in your logo and see how it really performs — on light, dark, colored and busy backgrounds, shrunk to favicon size, squinted, grayscaled and silhouetted, plus favicon, app-icon and avatar mockups. Get a smart visibility score with graded metrics and plain-English fixes. All analyzed on-device — nothing is uploaded.",
    keywords: [
      "logo visibility tester",
      "logo test tool",
      "favicon preview",
      "logo contrast checker",
      "logo on dark background",
      "logo legibility test",
    ],
    icon: ScanEyeIcon,
    category: "image",
  },
  {
    id: "codeshot",
    slug: "/tools/code-image",
    name: "Code Image Generator",
    shortName: "Code Image",
    description:
      "Turn any code snippet into a beautiful, shareable image — VS Code-grade syntax highlighting for 20+ languages via Shiki, real editor themes, window chrome, gradient backdrops, line numbers and retina PNG export. Perfect for X, slides, docs and READMEs. All on-device.",
    keywords: [
      "code image generator",
      "code to image",
      "code screenshot",
      "carbon alternative",
      "beautiful code snippets",
      "syntax highlight image",
    ],
    icon: Code2Icon,
    category: "developer",
  },
  {
    id: "blob",
    slug: "/tools/blob-generator",
    name: "Blob & Wave Generator",
    shortName: "Blobs & Waves",
    description:
      "Generate organic SVG blobs and layered section-divider waves — tune points, randomness, layers and amplitude, shuffle for endless variations, and pour in a gradient. Export crisp SVG, a CSS background snippet, or PNG. All on-device.",
    keywords: [
      "svg blob generator",
      "blob maker",
      "svg wave generator",
      "section divider svg",
      "organic shape generator",
      "css background shape",
    ],
    icon: ShapesIcon,
    category: "design",
  },
] as const satisfies readonly ToolMeta[];

/** Every valid tool id — derived from the registry above, never edit by hand. */
export type ToolId = (typeof TOOLS)[number]["id"];

// Object.fromEntries widens keys to string — the registry guarantees every ToolId is present.
export const TOOL_BY_ID = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
) as unknown as Record<ToolId, ToolMeta>;

/** Human labels, icons + display order for the tools-page category filter. */
export const TOOL_CATEGORIES: readonly {
  id: ToolCategory;
  label: string;
  icon: LucideIcon;
}[] = [
  { id: "links", label: "Links & QR", icon: LinkIcon },
  { id: "design", label: "Design", icon: PaintbrushIcon },
  { id: "color", label: "Color", icon: PaletteIcon },
  { id: "image", label: "Image", icon: ImageIcon },
  { id: "developer", label: "Developer", icon: Code2Icon },
];
